# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/R1hmpaTdno/australasia.  Olson data version 2012g
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Pacific::Apia;
{
  $DateTime::TimeZone::Pacific::Apia::VERSION = '1.51';
}

use strict;

use Class::Singleton 1.03;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Pacific::Apia::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
59279945216,
DateTime::TimeZone::NEG_INFINITY,
59279990400,
45184,
0,
'LMT'
    ],
    [
59279945216,
60273804416,
59279904000,
60273763200,
-41216,
0,
'LMT'
    ],
    [
60273804416,
61504572600,
60273763016,
61504531200,
-41400,
0,
'SAMT'
    ],
    [
61504572600,
63421182000,
61504533000,
63421142400,
-39600,
0,
'WST'
    ],
    [
63421182000,
63437436000,
63421146000,
63437400000,
-36000,
1,
'WSDT'
    ],
    [
63437436000,
63452556000,
63437396400,
63452516400,
-39600,
0,
'WST'
    ],
    [
63452556000,
63460922400,
63452520000,
63460886400,
-36000,
1,
'WSDT'
    ],
    [
63460922400,
63468885600,
63460972800,
63468936000,
50400,
1,
'WSDT'
    ],
    [
63468885600,
63484610400,
63468932400,
63484657200,
46800,
0,
'WST'
    ],
    [
63484610400,
63500940000,
63484660800,
63500990400,
50400,
1,
'WSDT'
    ],
    [
63500940000,
63516060000,
63500986800,
63516106800,
46800,
0,
'WST'
    ],
    [
63516060000,
63532389600,
63516110400,
63532440000,
50400,
1,
'WSDT'
    ],
    [
63532389600,
63547509600,
63532436400,
63547556400,
46800,
0,
'WST'
    ],
    [
63547509600,
63563839200,
63547560000,
63563889600,
50400,
1,
'WSDT'
    ],
    [
63563839200,
63578959200,
63563886000,
63579006000,
46800,
0,
'WST'
    ],
    [
63578959200,
63595288800,
63579009600,
63595339200,
50400,
1,
'WSDT'
    ],
    [
63595288800,
63610408800,
63595335600,
63610455600,
46800,
0,
'WST'
    ],
    [
63610408800,
63626738400,
63610459200,
63626788800,
50400,
1,
'WSDT'
    ],
    [
63626738400,
63641858400,
63626785200,
63641905200,
46800,
0,
'WST'
    ],
    [
63641858400,
63658188000,
63641908800,
63658238400,
50400,
1,
'WSDT'
    ],
    [
63658188000,
63673912800,
63658234800,
63673959600,
46800,
0,
'WST'
    ],
    [
63673912800,
63690242400,
63673963200,
63690292800,
50400,
1,
'WSDT'
    ],
    [
63690242400,
63705362400,
63690289200,
63705409200,
46800,
0,
'WST'
    ],
    [
63705362400,
63721692000,
63705412800,
63721742400,
50400,
1,
'WSDT'
    ],
    [
63721692000,
63736812000,
63721738800,
63736858800,
46800,
0,
'WST'
    ],
    [
63736812000,
63753141600,
63736862400,
63753192000,
50400,
1,
'WSDT'
    ],
    [
63753141600,
63768261600,
63753188400,
63768308400,
46800,
0,
'WST'
    ],
    [
63768261600,
63784591200,
63768312000,
63784641600,
50400,
1,
'WSDT'
    ],
    [
63784591200,
63799711200,
63784638000,
63799758000,
46800,
0,
'WST'
    ],
    [
63799711200,
63816040800,
63799761600,
63816091200,
50400,
1,
'WSDT'
    ],
    [
63816040800,
63831160800,
63816087600,
63831207600,
46800,
0,
'WST'
    ],
];

sub olson_version { '2012g' }

sub has_dst_changes { 15 }

sub _max_year { 2022 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}

sub _last_offset { 46800 }

my $last_observance = bless( {
  'format' => 'WS%sT',
  'gmtoff' => '13:00',
  'local_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 734594,
    'local_rd_secs' => 10800,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 734594,
    'utc_rd_secs' => 10800,
    'utc_year' => 2013
  }, 'DateTime' ),
  'offset_from_std' => 0,
  'offset_from_utc' => 46800,
  'until' => [],
  'utc_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 734593,
    'local_rd_secs' => 50400,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 734593,
    'utc_rd_secs' => 50400,
    'utc_year' => 2013
  }, 'DateTime' )
}, 'DateTime::TimeZone::OlsonDB::Observance' )
;
sub _last_observance { $last_observance }

my $rules = [
  bless( {
    'at' => '4:00',
    'from' => '2012',
    'in' => 'Apr',
    'letter' => '',
    'name' => 'WS',
    'offset_from_std' => 0,
    'on' => 'Sun>=1',
    'save' => '0',
    'to' => 'max',
    'type' => undef
  }, 'DateTime::TimeZone::OlsonDB::Rule' ),
  bless( {
    'at' => '3:00',
    'from' => '2012',
    'in' => 'Sep',
    'letter' => 'D',
    'name' => 'WS',
    'offset_from_std' => 3600,
    'on' => 'lastSun',
    'save' => '1',
    'to' => 'max',
    'type' => undef
  }, 'DateTime::TimeZone::OlsonDB::Rule' )
]
;
sub _rules { $rules }


1;

