/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /Users/ariel/git/darling/src/external/perl/5.18/perl/miniperl ../bin/enc2xs -Q -o ji_04_t.c -f ji_04_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t jis0212_raw_encoding;
