# 
# /*
#  * *********** WARNING **************
#  * This file generated by ModPerl::WrapXS/0.01
#  * Any changes made here will be lost
#  * ***********************************
#  * 01: lib/ModPerl/Code.pm:716
#  * 02: /Library/Caches/com.apple.xbs/Binaries/apache_mod_perl/apache_mod_perl-109~228/TempContent/Objects/mod_perl-2.0.9/blib/lib/ModPerl/WrapXS.pm:635
#  * 03: /Library/Caches/com.apple.xbs/Binaries/apache_mod_perl/apache_mod_perl-109~228/TempContent/Objects/mod_perl-2.0.9/blib/lib/ModPerl/WrapXS.pm:1186
#  * 04: Makefile.PL:435
#  * 05: Makefile.PL:333
#  * 06: Makefile.PL:59
#  */
# 


package ModPerl::Interpreter;

use strict;
use warnings FATAL => 'all';



use Apache2::XSLoader ();
our $VERSION = '2.000009';
Apache2::XSLoader::load __PACKAGE__;



1;
__END__
