/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /Users/ariel/git/darling/src/external/perl/5.28/perl/miniperl ../bin/enc2xs -Q -o ks_03_t.c -f ks_03_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t ksc5601_raw_encoding;
