/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /Users/ariel/git/darling/src/external/perl/5.28/perl/miniperl ../bin/enc2xs -Q -O -o ebcdic_t.c -f ebcdic_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t cp1026_encoding;
extern encode_t cp1047_encoding;
extern encode_t cp37_encoding;
extern encode_t cp500_encoding;
extern encode_t cp875_encoding;
extern encode_t posix_bc_encoding;
