/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /Users/ariel/git/darling/src/external/perl/5.18/perl/miniperl ../bin/enc2xs -Q -o cp_00_t.c -f cp_00_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t cp949_encoding;
