/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /Users/ariel/git/darling/src/external/perl/5.18/perl/miniperl ../bin/enc2xs -Q -o bi_01_t.c -f bi_01_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t big5_hkscs_encoding;
