/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /Users/ariel/git/darling/src/external/perl/5.28/perl/miniperl ../bin/enc2xs -Q -o gb_02_t.c -f gb_02_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t gb12345_raw_encoding;
